    DELETE FROM [dbo].[Questions]
    DELETE FROM [QuestionConfigurations]
    DELETE FROM [dbo].[Feedbacks]
    INSERT INTO [dbo].[Feedbacks] ([TotalApplicants]) VALUES (0)
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (1,'a',0,'StackOverflow',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (1,'b',0,'Indeed',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (1,'c',0,'Other',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (2,'a',0,'Easy to access by public transport',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (2,'b',0,'Easy to access by car',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (2,'c',0,'In a pleasant area',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (2,'d',0,'None of the above',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (3,'a',0,'Tidy',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (3,'b',0,'Sloppy',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (3,'c',0,'Did not notice',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (4,'a',0,'Very difficult',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (4,'b',0,'Difficult',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (4,'c',0,'Moderate',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (4,'d',0,'Easy',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (5,'a',0,'Enthusiastic',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (5,'b',0,'Polite',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (5,'c',0,'Organized',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[Questions] ([QuestionNumber] ,[QuestionAnswer] ,[QuestionFeedbackTotal] ,[QuestionDisplay] ,[Feedback_FeedbackId]) VALUES (5,'d',0,'Could not tell',(SELECT TOP 1 FeedbackId FROM FEEDBACKS))
    INSERT INTO [dbo].[QuestionConfigurations] ([Question] ,[QuestionNumber] ,[QuestionAlpahRange] ,[Feedback_FeedbackId] ,[QuestionTypeDescription]) VALUES ('How did you find out about this job opportunity?',1,'abc',(SELECT TOP 1 FeedbackId from Feedbacks),'(single choice)')
    INSERT INTO [dbo].[QuestionConfigurations] ([Question] ,[QuestionNumber] ,[QuestionAlpahRange] ,[Feedback_FeedbackId] ,[QuestionTypeDescription]) VALUES ('How do you find the company’s location?',2,'abcd',(SELECT TOP 1 FeedbackId from Feedbacks),'(multiple choice)')
    INSERT INTO [dbo].[QuestionConfigurations] ([Question] ,[QuestionNumber] ,[QuestionAlpahRange] ,[Feedback_FeedbackId] ,[QuestionTypeDescription]) VALUES ('What was your impression of the office where you had the interview?',3,'abc',(SELECT TOP 1 FeedbackId from Feedbacks),'(single choice)')
    INSERT INTO [dbo].[QuestionConfigurations] ([Question] ,[QuestionNumber] ,[QuestionAlpahRange] ,[Feedback_FeedbackId] ,[QuestionTypeDescription]) VALUES ('How technically challenging was the interview?',4,'abcd',(SELECT TOP 1 FeedbackId from Feedbacks),'(single choice)')
    INSERT INTO [dbo].[QuestionConfigurations] ([Question] ,[QuestionNumber] ,[QuestionAlpahRange] ,[Feedback_FeedbackId] ,[QuestionTypeDescription]) VALUES ('How can you describe the manager that interviewed you?',5,'abcd',(SELECT TOP 1 FeedbackId from Feedbacks),'(multiple choice)')
